version: '3'

networks:
  default:
    external:
      name: npmnetwork

services:
  dodge:
    image: 'junorr/dodge:0.1'
    restart: unless-stopped
    #ports:
    #  - '127.0.0.1:5000:5000'
    expose:
      - 5000
    environment:
      - DODGE_MODE=server
      - DODGE_LISTEN_ADDRESS=0.0.0.0:5000
